
#ifndef SOCKET__SHARED_H
#define SOCKET__SHARED_H

//#define SERVER_ADDRESS_STR INADDR_ANY
#define SERVER_PORT_SENDER 0
#define SERVER_PORT_RECIEVER 0

#define SENDER_PACKET_SIZE 4 
#define RECIEVER_PACKET_SIZE 6
#define ACTUAL_PACKET_SIZE 31
#define PACKET_SIZE_CONTAINER 32
#define NO_PACKETS_TOGETHER 4
#define NO_BITS_BEFORE_ENCODE 26
#define NO_LETTERS_PACKET 13

//#define S123 "127.0.0.1"


#endif 